### ISSUE TITLE
Uncaught Error: Invalid pixel coordinate (react-map-gl@5.0.4)

### ISSUE THREAD

**Issue by adrienj** [uber/react-map-gl#846]
Cause:
If you switch from a component rendering the map to another (click on the switch button in the link I provided), then right clicking on map causes an error, then subsequent mouse-move on the map cause the error too. If you do this mutliple times, multiple errors are triggered at the same time, as though the event handlers accumulate.

Result:
```
assert.js:10 Uncaught Error: invalid pixel coordinate
    at assert (assert.js:10)
    at pixelsToWorld (web-mercator-utils.js:240)
    at WebMercatorViewport.unproject (viewport.js:109)
    at InteractiveMap._normalizeEvent (interactive-map.js:438)
    at eval (interactive-map.js:251)
    at EventRegistrar._emit (event-registrar.js:125)
    at EventRegistrar.handleEvent (event-registrar.js:97)
    at Manager.emit (hammer.js:2631)
    at EventManager._onBasicInput (event-manager.js:387)
    at Manager.emit (hammer.js:2631)
    at PointerEventInput.inputHandler [as callback] (hammer.js:590)
    at PointerEventInput.PEhandler (hammer.js:990)
    at PointerEventInput.handler (hammer-overrides.js:56)
    at Input.domHandler (hammer.js:507)
```

To reproduce:
https://codesandbox.io/s/wonderful-violet-vnt6y 
I'm on Chrome 75.0.3770.100 64bits, OSX 10.14
And Firefox 68.0

**Comment by Pessimistress** [comment]
This is an interesting bug... We do not remove event listeners upon unmount because we assume the element that they are attached to will be disposed. With your sandbox I can *sometimes* reproduce the issue, maybe React is doing something funky under the hood...

**Comment by xintongxia** [comment]
fixed in 5.0.7

**Comment by amygroshek** [comment]
I am running into this with v4.1.13

**Comment by amygroshek** [comment]
I can replicate this in 5.0.7

**Comment by limZyuan** [comment]
Currently using version 5.2.3, could reproduce the pixel error when dragging map with both right and left mouse button down.

**Comment by titivermeesch** [comment]
It seems that this issue is still present on 6.1.11. A few users are triggering this issue. Still investigating when this happens

**Comment by Morganballat** [comment]
Please let me know if you fixed it

**Comment by andeplane** [comment]
@Morganballat I just got this issue because the div containing the map had 0 pixels height.
